# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Official Release

on:
  release:
    types: [published]

jobs:
  publish-npm-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      # Only publish when tag does not include beta or rc suffix
      - run: if [[ ${TAG_NAME} =~ ^v[0-9]+.[0-9]+.[0-9]+$ ]]; then npm run build && cd dist/cloudflare-stream && npm publish; fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          TAG_NAME: ${{github.event.release.tag_name}}
